org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

plugin_group=Amazonia
plugin_description=DestriumPlugin is a Plugin based on Exploration, Building, Tools and Machines !
plugin_author=NuyyKatazou
plugin_website=
plugin_main_entrypoint=fr.amazonia.DestriumPlugin
server_version=*
plugin_name=DestriumMod
plugin_version=0.0.5-SNAPSHOT
#Version 4